### ISSUE TITLE
Regarding parameter ‘task’ in main.py and model.py

### ISSUE THREAD

**Issue by UnBuen** [debadyuti23/GraphCovidNet#2]
Hi @debadyuti23 , @thepritam ,
 
Thank you for your outstanding contributions in this paper. 

I have a question about the specific role of the parameter "task". When task==‘node’ and task==‘graph’, what is the difference between them and what will be the impact?

Looking forward to your reply.

Best,
Unbuen

**Comment by RRuschel** [comment]
@UnBuen I've been trying to understand that as well. It seems that if task is node, the network will try to predict unlabeled nodes on the graph. If the task is graph, then the predictions are going to be graph-level.
But again, take this with a grain of salt because I'm still working around the code

**Comment by UnBuen** [comment]
> @UnBuen I've been trying to understand that as well. It seems that if task is node, the network will try to predict unlabeled nodes on the graph. If the task is graph, then the predictions are going to be graph-level. But again, take this with a grain of salt because I'm still working around the code

@RRuschel Thank you for your help. I agree with your statement. It can be explained on page 12 of the paper. I wish you success in your studies.

Best,
Unbuen.
